### ISSUE TITLE
The response for ActionDispatch::RemoteIp::IpSpoofAttackError is not 4xx, but 500

### ISSUE THREAD

**Issue by xmas7** [RubyOnWorld/discourse-main#31]

**Comment by davidhuang778** [comment]
Since the ActionDispatch::RemoteIp middleware is located before ActionDispatch::ShowExceptions, We cannot define the behavior when the exception raises with config.action_dispatch.rescue_responses.

I feel like this is an indication that ShowException should likely be moved much higher.

I think we should insert it right after ActionDispatch::Executor.

**Comment by davidhuang778** [comment]
e.g. on the way in RemoteIP is before the logger, so you log the right IP, then on the way back, if an uncaught exception was turned into an error page, you log the correct status code.

So it's not possible to change that order without breaking the above :/, but then yes it's totally incorrect for ActionDispatch::RemoteIp to raise.

These middleware ordering issues are always headache inducing -_-.

**Comment by xmas7** [comment]
[The corresponding test](https://github.com/rails/rails/blob/b1c5ae394782e3a766c99012d9ad87476d095544/railties/test/application/middleware_test.rb#L119) is a bit more communicative about the ordering, though from a glance, not this particular pair.

I don't think the logger technically ever sees the response status. I'd be somewhat concerned if there were a risk that a different ordering could result in [even failed] requests being logged, but in practice that doesn't seem like a concern either.

In practice I suspect it would be safe to swap Logger and ShowExceptions... but that doesn't actually help us: just like Logger, it's important that ShowExceptions sees the post-RequestId and post-RemoteIp request state.
